### PR TITLE
Fix for slack 4.0.0

### PR DESCRIPTION
**Pull request by alinoancea**
If someone can test this in other windows version, that would be great. I tested on Windows 10 x64.

Some feedback would be great :smile:

### CODE REVIEW

**Comment by alinoancea** [comment]
README.md should be changed accordingly (I'll try to do that later)

**Comment by morbus** [comment]
This has worked on two different machines for me.

1. First, on a Windows 10 VM where I installed npm and ran the script.
2. Second, I shared the revised app.asar with a coworker, who dropped it into place on their non-npm Win10 machine.

**Comment by somanysteves** [comment]
I got an error with it...
```
CMD /C "ASAR pack C:\Users\steve\AppData\Local\Temp\temp-15002\app C:\Users\steve\AppData\Local\Temp\temp-15002\app.asar"
C:\Users\steve\AppData\Roaming\npm\node_modules\asar\lib\asar.js:29
module.exports.createPackage = async function (src, dest) {
                                     ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\steve\AppData\Roaming\npm\node_modules\asar\bin\asar.js:2:12)
```
Maybe a node versioning thing?

**Comment by alinoancea** [comment]
Hi @imjuststeve,

Can you tell me what version on Windows and node are you using?

**Comment by imjuststeve** [comment]
Windows 10, node v6.17.1 :(
I'd upgrade but I"m afraid to break our legacy builds

**Comment by somanysteves** [comment]
@alinoancea 
Windows 10, node v6.17.1 :(
I'd upgrade but I"m afraid to break our legacy builds

**Comment by batjko** [comment]
> node v6.17.1 :(

Can you transpile from a higher version (i.e. using Babel)?

**Comment by Jayhachi** [comment]
I've tried running the Windows script on two different Win 10 x64 machines to no avail. one with Node 10.16.0 and the other with 12.6.0. I see "Dark theme installed...Please restart slack." although upon restarting am not seeing the desired results. I've noticed the modified date of app.asar has changed to the time of running the script as well. Is there something I'm missing here by chance?

**Comment by alinoancea** [comment]
What version of slack are you using? This method is not working on slack beta version 4.0.0

**Comment by Jayhachi** [comment]
I'm using Production 4.0.0 64-bit. I tried uninstalling and reinstalling before running the script again. It initially auto updated on both my machines and I didn't check version before uninstalling and reinstalling.

**Comment by alinoancea** [comment]
Can you reboot the machine after the script is completed, please? Maybe the slack doesn't know, for some reason, that the archive has changed.

**Comment by maturner1** [comment]
The script runs just fine on my Win10 x64 with Node 12.6.0, however, upon restarting Slack, it just sits at the opening screen with a spinning wheel.

**Comment by maturner1** [comment]
After re-installing Slack, this script works just fine.

**Comment by alinoancea** [comment]
Would you upload app.asar archive from `C:\Users\<username>\AppData\Local\slack\app-[4.x.x]\resources` so I can check it out? The infinite spinning wheel happened to me when the script was ran multiple times inserting the `listener.js` one after another in `ssb-interop.bundle.js` without checking if it's already there (that issue should be fixed tho)

**Comment by maturner1** [comment]
Sorry, too late. My troubleshooting immediately kicked in when it didn't work and I went and did a fresh Slack install.

**Comment by Jayhachi** [comment]
Tried rebooting (actually shut down) and still no change. Tried uninstalling, deleting slack directory within ```C:\Users\username\AppData\Local``` and rebooting once more before installing again. I ran the script again, and reboot afterward.

**Comment by alinoancea** [comment]
Ok, can you please upload the `app.asar` archive from `slack` folder, after you run the script?

**Comment by Jayhachi** [comment]
```app.asar``` attached. Apologies if there's something glaringly obvious that I failed to carry out successfully.
[app.zip](https://github.com/earlduque/Slack-Dark-Theme/files/3403686/app.zip)

**Comment by alinoancea** [comment]
@Jayhachi, I downloaded your archive and replace mine on a clean Windows with a clean Slack installation. Everything is working fine. I will try some other things tomorrow and I'll keep you posted. Sorry for the inconvenience. :disappointed:

**Comment by Jayhachi** [comment]
@alinoancea I'm inconveniencing you I feel. Thanks for looking into it and I'll try the same on the other machine to see if I fare any better there when I get a chance.

**Comment by broodfusion** [comment]
Anyone tested this on a Mac?

**Comment by alinoancea** [comment]
Hi @Jayhachi, sorry for coming back so late, I'm got busy at work. Did you have time to take a look at your other machine? I can't think of another solution for the one that is not working, I'm sorry. If anyone has other thoughts about this and would like to share, it would be great.

**Comment by jingofett** [comment]
I don't think this is working with Slack 4.0.1 (I know it says for 4.0.0 but I thought I'd let you know) running on W10 x64, with Node JS 12.7

EDIT:

Nevermind, needed to reset the app by going to Help -> Troubleshooting -> Reset App as mentioned here:
https://github.com/earlduque/Slack-Dark-Theme/issues/35#issuecomment-513420721

**Comment by benjamhooper** [comment]
If you're using windows use this in powershell (running in Administrator mode):
```
iex (new-object net.webclient).downloadstring('https://raw.githubusercontent.com/benjamhooper/slack-custom-theme/master/slackcustomtheme.ps1')
```

Run this for a custom slack theme, just use this repo's theme. The raw link: https://raw.githubusercontent.com/earlduque/Slack-Dark-Theme/master/dark.css

If you have issues, please visit here: https://github.com/benjamhooper/slack-custom-theme

**Pull request merged**
